tinkerhub/platform

apps/api/prisma/migrations/20220928134852_platform/migration.sql
apps/api/prisma/migrations/20220928173939_platform/migration.sql
apps/api/prisma/schema.prisma
apps/api/src/profiles/dto/create-profile.dto.ts

Describe the technical changes you did.
Describe the issue you are solving.
Provide information about the environment and the path to verify the behaviour.
Let us know if this is related to any issue/pull request
Kindly attach screenshot of UI changes made.

feat: pass-year added

---

apps/api/src/profiles/profiles.controller.ts
apps/api/src/profiles/profiles.service.ts

Describe the technical changes you did.
Describe the issue you are solving.
Provide information about the environment and the path to verify the behaviour.
Let us know if this is related to any issue/pull request
Kindly attach screenshot of UI changes made.

feat: college search added

---

apps/api/src/noco/noco.controller.ts
apps/api/src/noco/noco.service.ts
apps/api/src/profiles/dto/create-profile.dto.ts
apps/api/src/profiles/profiles.controller.ts
apps/api/src/profiles/profiles.service.ts

1. Changed connectOrCreate to create (user - skill relation)
2. Updated DTO
3. Case fixes
1. For more security and easy to call from frontend

fix: changed to connect and fixed dto and case

---

apps/api/package.json
apps/api/src/app.module.ts
apps/api/src/noco/noco.controller.ts
apps/api/src/profiles/profiles.controller.ts
apps/api/src/profiles/profiles.service.ts
docker-compose.yml
pnpm-lock.yaml

* Added Rate Limiter for api
* To save the api from brute force attacks
Just run the api with the command ``pnpm --filter api dev``

feat: added rate limiter

---

apps/web/pages/auth/[[...paths]].tsx
apps/web/pages/profile.tsx
apps/web/pages/wizard.tsx
apps/web/theme/index.ts
apps/web/views/wizard/components/Final.tsx
apps/web/views/wizard/validator.ts

* removed unwanted routing
*  changed color mode from dark -> light
* fixed college validation
*  fixed font size of  membership id in smaller screens

fix: unwanted routing

---

apps/web/views/profile/components/RowTwo.tsx
apps/web/views/wizard/components/Two.tsx

Added Debouncing for college & Skills selects in Profile & Wizard page

fix: debounce

---

apps/web/context/Auth/index.tsx
apps/web/pages/auth/[[...paths]].tsx
apps/web/views/profile/components/RowThree.tsx
apps/web/views/profile/components/RowTwo.tsx
apps/web/views/wizard/components/Final.tsx
apps/web/views/wizard/components/Three.tsx
apps/web/views/wizard/validator.ts
docker-compose.yml

changed pincode type
docker file name
toast type
toast showing error

fix: toast,spacing,pincode

---

apps/web/pages/auth/[[...paths]].tsx
apps/web/pages/profile.tsx
apps/web/views/profile/components/ProfileBar.tsx

added loader on otp submission
added button disadled to prevent user from canceling the edit if error exist

feat: added loader on otp submission

---

apps/api/prisma/migrations/20221120085500_init2/migration.sql
apps/api/prisma/migrations/20221205165128_init/migration.sql
apps/api/prisma/migrations/20230216141619_init/migration.sql
apps/api/prisma/migrations/20230216165856_init/migration.sql
apps/api/prisma/migrations/20230216171927_user_id_corrected/migration.sql
apps/api/prisma/migrations/20230216172540_id_autogenerate/migration.sql
apps/api/prisma/schema.prisma
apps/api/src/main.ts
apps/api/src/noco/noco.service.ts
docker-compose.yml

1. Autogenerate ids for skills and college
2. SuperTokens multiple web domains
3. Prisma searching made case insensitive

feat: id autogenerate and multiple supertokens domain

---

apps/web/context/Auth/index.tsx
apps/web/pages/profile.tsx
apps/web/pages/wizard.tsx

changed pin payload to number or undefined so that dto wont verify it

fix: dto error on pin type

---

apps/web/layout/BaseLayout.tsx
apps/web/layout/components/Footer.tsx

added netlify badge
<a href="https://www.netlify.com">
<img
src="https://www.netlify.com/v3/img/components/netlify-color-accent.svg"
alt="Deploys by Netlify"
</a>

feat(web): added netlify badge on footer

---

.vscode/settings.json
apps/web/pages/profile.tsx
apps/web/pages/wizard.tsx
apps/web/views/profile/components/RowOne.tsx
apps/web/views/profile/components/RowTwo.tsx
apps/web/views/wizard/components/Final.tsx
apps/web/views/wizard/components/Lottie.tsx
apps/web/views/wizard/components/Two.tsx
apps/web/views/wizard/validator.ts
pnpm-lock.yaml

* changed validation type of mentor id didnt worked before
*  added callback on lottie anim'
*  fixed succes age margin issue on small screens
*  pincode problem actually exist on backend

fix(web): lottie animation,mentor validation,email input

---

apps/api/package.json
apps/api/src/auth/supertokens/supertokens.service.ts
pnpm-lock.yaml

Added supertokens dashboard recipe
To view for user auth details especially during migration 
visit ``locahost:/auth/dashboard``

chore: superTokens dashboard added

---

apps/api/prisma/migrations/20230318212443_college_table_update/migration.sql
apps/api/prisma/migrations/20230318214050_college_table_update/migration.sql
apps/api/prisma/migrations/20230318220113_typo_fixed_for_college_table/migration.sql
apps/api/prisma/migrations/20230321103017_added_enum/migration.sql
apps/api/prisma/schema.prisma
apps/api/src/noco/noco.controller.ts
apps/api/src/noco/noco.service.ts
apps/api/src/profiles/dto/create-profile.dto.ts
apps/api/src/profiles/exception/create-college.exception.ts
apps/api/src/profiles/profiles.service.ts

1. Created a function to create a new college if college not found
2. Changed findFirst to findUnique in prisma

feat: create new college

---

apps/web/pages/404.tsx
apps/web/pages/profile.tsx
apps/web/pages/wizard.tsx
apps/web/views/profile/components/RowTwo.tsx
apps/web/views/wizard/components/Two.tsx
apps/web/views/wizard/validator.ts

fix: added link to route on 404 page, added create college manually in web

---

apps/api/src/noco/noco.controller.ts
apps/api/src/noco/noco.service.ts
apps/api/src/profiles/exception/college.create.exception.ts
apps/api/src/profiles/exception/college.search.exception.ts
apps/api/src/profiles/exception/create.user.exception.ts
apps/api/src/profiles/exception/read.user.exception.ts
apps/api/src/profiles/exception/skill.search.exception.ts
apps/api/src/profiles/exception/update.user.exception.ts
apps/api/src/profiles/profiles.controller.ts
apps/api/src/profiles/profiles.service.ts

Added error handler for noco controller
Standardized the response
Corrected the variable names

Feat error handler

---

apps/web/pages/profile.tsx
apps/web/pages/wizard.tsx

fix: added error handler on college creation

---

apps/web/views/profile/components/RowTwo.tsx

copied the previous pr to add that feature in the profile edit section
Describe the technical changes you did.
Describe the issue you are solving.
Provide information about the environment and the path to verify the behaviour.
Let us know if this is related to any issue/pull request
Kindly attach screenshot of UI changes made.

feat: added passout year in the profile edit section

---

apps/web/views/profile/components/ProfileBar.tsx

Made the github button row responsive.

fix(web): github button fixed

---

src/api/firebase.ts
src/components/animation/Pulse.tsx
src/components/copy/index.tsx
src/layout/BaseLayout.tsx
src/layout/EventsLayout.tsx
src/layout/ProfileLayout.tsx
src/layout/components/TopBar.tsx
src/layout/components/Topbar.tsx
src/layout/components/index.ts
src/pages/404.tsx
src/pages/_app.tsx
src/pages/_document.tsx
src/pages/events.tsx
src/pages/profile.tsx
src/pages/wizard.tsx
src/types/index.ts
src/views/events/components/CreateTeamModal.tsx
src/views/events/components/JoinTeamModal.tsx
src/views/profile/components/ProfileBar.tsx
src/views/profile/components/RowOne.tsx
src/views/profile/components/RowThree.tsx
src/views/profile/types.ts
src/views/wizard/components/Card.tsx
src/views/wizard/components/Final.tsx
src/views/wizard/components/Quotes.tsx

Describe the technical changes you did.
Describe the issue you are solving.
Provide information about the environment and the path to verify the behaviour.
Let us know if this is related to any issue/pull request
Kindly attach screenshot of UI changes made.

Running events

---

src/pages/events.tsx
src/views/events/components/CreateTeamModal.tsx

Nothing much, just changed team size in events page and then changed color of a link to blue.

Change text and adjust color

---

src/pages/events.tsx
src/pages/profile.tsx
src/views/profile/components/RowOne.tsx
src/views/profile/components/RowTwo.tsx

Working PR
